# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do

  desc "Increment android version"
  lane :increment_version do
    increment_version_code
  end

  desc "Submit a new Beta Build to Google Play"
  lane :internal do
        aws_s3(
          access_key:  "test",
          secret_access_key: "test",
          bucket:  'dock-wallet',
          region: 'us-west-1',
          apk: "/home/runner/work/dock-app/dock-app/android/app/build/outputs/apk/release/app-release.apk",
          app_directory: 'android-apks',
          upload_metadata: true,
          acl: 'private',
        )

  end
end


