name: Android Release
on:
  pull_request:
    types: [closed]
    branches:
      - "deploy"
jobs:
  internal_release_android:
    runs-on: ubuntu-latest
    # if: github.event.pull_request.merged == true
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          token: "${{ secrets.GIT_ACCESS_TOKEN }}"

      # - name: Setup node
      #   uses: actions/setup-node@v1
      #   with:
      #     node-version: '15.x'

      # - uses: actions/setup-ruby@v1
      #   with:
      #     ruby-version: '2.x'

      # - name: Install and lint
      #   run: |
      #     git config --global url."https://".insteadOf git://
      #     echo fs.inotify.max_user_watches=524288 | sudo tee -a /etc/sysctl.conf && sudo sysctl -p
      #     yarn install
      #     yarn postinstall
      #     rm -rf ./certs
      #     git clone "https://${{ secrets.ACCESS_TOKEN }}@github.com/docknetwork/dock-app-certs.git" ./certs
      #     mv ./certs/google-play.json ./
      #     cp -rf ./certs/google-services.json ./android/app/
      #     rm -rf ./android/gradle.properties
      #     cp -rf ./certs/gradle.properties ./android/gradle.properties
      #     # Pull env variables from certs repo
      #     # It will inject sentry token in the JS thread
      #     cp -rf ./certs/.env ./
      #     rm -rf /tmp/google-play-cert
      #     cp -rf ./certs/google-play-cert /tmp/google-play-cert

      # - name: Install Fastlane
      #   run: gem install fastlane

      - name: Release
        env:
          S3_ACCESS_KEY: ${{ secrets.S3_ACCESS_KEY }}
          S3_SECRET_ACCESS_KEY: ${{ secrets.S3_SECRET_ACCESS_KEY }}
          S3_APP_BUCKET: ${{ secrets.S3_APP_BUCKET }}
          S3_REGION: ${{ secrets.S3_REGION }}
          S3_ANDROID_APK_DIR: ${{ secrets.S3_ANDROID_APK_DIR }}
          S3_ACL: ${{ secrets.S3_ACL }}
        run: |
          echo "PR: ${{ github.event.number  }}" > test.gradle
          echo "test"
          # cd ./android
          # fastlane increment_version
          # fastlane send_message

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: (CI) Android deploy
          file_pattern: "*.gradle"