name: Code check
on: [push]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'

      - name: Install and lint
        run: |
          yarn install --frozen-lockfile --ignore-scripts
          yarn lint
          
      - name: Unit tests
        run: |
          yarn test