name: Code check
on:
  push:
    branches:
      - "!*"
    tags:
      - "v*"
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: '15.x'

      - name: Install and lint
        run: |
          git config --global url."https://".insteadOf git://
          yarn install
          yarn lint

      - name: Unit tests
        run: |
          yarn test
